### ISSUE TITLE
Cannot connect to rTorrent

### ISSUE THREAD

**Issue by albertoxamin** [Wonderfall/docker-rtorrent-flood#15]
I built the docker image to update to the latest version of flood but I'm welcomed with this message 
![image](https://user-images.githubusercontent.com/6067659/72532188-3df3be00-3873-11ea-969d-208d7cdd5a36.png)

**Comment by patrick-othmer** [comment]
Hi @albertoxamin 

you need to select "Unix Socket". Path is: `/tmp/rtorrent.sock`

**Comment by albertoxamin** [comment]
Thanks

**Comment by zexa** [comment]
I had the same issue. It would be wise to include this in the README.
