### ISSUE TITLE
Provide a SCGI Mount Point

### ISSUE THREAD

**Issue by al3xLvs** [Wonderfall/docker-rtorrent-flood#5]
Flood doesn't use scgi mount point for communicate with rtorrent.
But some other apps use this like transdrone (or my script 😅 )

It's possible to provide this? with a web server or via nodejs whatever.

**Comment by jockef3000** [comment]
Im also intrested in thix

**Comment by hergonoway** [comment]
+1

**Comment by pawndev** [comment]
Hi @Magicalex , any news about this ? 😅
